name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          cd run_motr_in_magpie/demo
          npm install --legacy-peer-deps
          npm install git+https://github.com/cuierd/magpie-base-MoTR.git#main --save

      - name: Build project
        run: |
          cd run_motr_in_magpie/demo
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build || {
            mkdir -p dist
            echo "<h1>临时页面</h1>" > dist/index.html
          }

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # 专门用于部署的分支
          folder: run_motr_in_magpie/demo/dist
          token: ${{ secrets.GITHUB_TOKEN }}